import math
import random
from typing import List, Tuple

# =====================================================================
# CONFIGURATION INTEGRATION & FALLBACKS
# =====================================================================
try:
    from config import DEFAULT_WIDTH, DEFAULT_HEIGHT, CUSTOM_OBSTACLES
except ImportError:
    DEFAULT_WIDTH, DEFAULT_HEIGHT = 20, 15
    CUSTOM_OBSTACLES = []  # Fallback to an empty list if config is missing

class SurgicalLabEnvironment:
    """Surgical lab grid with preset test cases, fixed obstacles, custom editor maps, or procedural generation"""
    
    def __init__(self, map_type: str = 'custom', width: int = DEFAULT_WIDTH, height: int = DEFAULT_HEIGHT, obstacle_density: float = 0.25):
        self.width = width
        self.height = height
        self.grid = [[0 for _ in range(width)] for _ in range(height)]
        self.map_type = map_type.lower()
        
        # Route mapping generation based on selected configuration
        if self.map_type == 'custom':
            self._load_custom_obstacles()
        elif self.map_type == 'random':
            self._generate_random_obstacles(obstacle_density)
        elif self.map_type == 'surgical':
            self._add_fixed_surgical_obstacles()
        elif self.map_type in ['trivial', 'island', 'trap', 'alternative']:
            self._load_test_case_presets()
        else:
            raise ValueError(
                f"Unknown map_type: '{map_type}'. "
                f"Choose from 'custom', 'surgical', 'random', 'trivial', 'island', 'trap', 'alternative'"
            )
            
    def _load_custom_obstacles(self):
        """Injects custom map layouts generated by the interactive visual tool"""
        if not CUSTOM_OBSTACLES:
            print("Notice: No custom obstacles found in config.py. Initializing empty grid.")
            return

        for x, y in CUSTOM_OBSTACLES:
            # Defensive validation check prevents bad configs from causing index crashes
            if self.is_valid_coord(x, y):
                self.grid[y][x] = 1
            else:
                print(f"Warning: Obstacle coordinate ({x}, {y}) skipped because it is out of grid bounds.")

    def _add_fixed_surgical_obstacles(self):
        """Add realistic fixed surgical lab obstacles"""
        # Operating tables
        for x in range(5, 8):
            for y in range(3, 6): self.grid[y][x] = 1
        # Equipment carts
        for x in range(12, 15):
            for y in range(8, 10): self.grid[y][x] = 1
        # Sterile supply cabinets
        for x in range(2, 4):
            for y in range(10, 13): self.grid[y][x] = 1
        # Anesthesia machine & extra objects
        self.grid[2][15] = self.grid[2][16] = 1
        for x, y in [(7, 12), (8, 12), (14, 5), (15, 5), (10, 2), (11, 2)]:
            if self.is_valid_coord(x, y): self.grid[y][x] = 1

    def _generate_random_obstacles(self, density: float):
        """Procedurally creates a random map based on target density percentage"""
        total_cells = self.width * self.height
        target_obstacles = int(total_cells * density)
        
        count = 0
        while count < target_obstacles:
            x = random.randint(0, self.width - 1)
            y = random.randint(0, self.height - 1)
            
            if (x, y) not in [(0, 0), (self.width - 1, self.height - 1)] and self.grid[y][x] == 0:
                self.grid[y][x] = 1
                count += 1

    def _load_test_case_presets(self):
        """Injects explicit deterministic configurations for lab test validations"""
        self.width = 10
        self.height = 10
        self.grid = [[0 for _ in range(self.width)] for _ in range(self.height)]
        
        if self.map_type == 'trivial':
            pass
        elif self.map_type == 'island':
            for x in range(7, 10):
                self.grid[7][x] = 1
            self.grid[8][7] = 1
            self.grid[9][7] = 1
        elif self.map_type == 'trap':
            for y in range(2, 8):
                self.grid[y][5] = 1
            self.grid[2][4] = self.grid[2][3] = 1
            self.grid[7][4] = self.grid[7][3] = 1
        elif self.map_type == 'alternative':
            for y in range(0, 8):
                self.grid[y][4] = 1
            self.grid[2][7] = self.grid[3][7] = 1

    def is_valid_coord(self, x: int, y: int) -> bool:
        """Helper to check array boundaries safely before inspecting grid value"""
        return 0 <= x < self.width and 0 <= y < self.height

    def is_valid(self, x: int, y: int) -> bool:
        return self.is_valid_coord(x, y) and self.grid[y][x] == 0
    
    def get_neighbors(self, x: int, y: int) -> List[Tuple[int, int]]:
        directions = [(0, 1), (1, 0), (0, -1), (-1, 0)]
        return [(x + dx, y + dy) for dx, dy in directions if self.is_valid(x + dx, y + dy)]
    
    def manhattan_distance(self, x1: int, y1: int, x2: int, y2: int) -> float:
        return abs(x1 - x2) + abs(y1 - y2)
        
    def euclidean_distance(self, x1: int, y1: int, x2: int, y2: int) -> float:
        return math.sqrt((x1 - x2)**2 + (y1 - y2)**2)

    def print_grid(self, start: Tuple[int, int] = None, goal: Tuple[int, int] = None, path: List[Tuple[int, int]] = None):
        """Terminal printing helper to render obstacles (█), path (·), Start (S), and Goal (G)"""
        path_set = set(path) if path else set()
        
        print("\n" + "=" * (self.width * 2 + 2))
        for y in range(self.height):
            row_str = "|"
            for x in range(self.width):
                coord = (x, y)
                if coord == start:
                    row_str += "S "
                elif coord == goal:
                    row_str += "G "
                elif coord in path_set:
                    row_str += "· "
                elif self.grid[y][x] == 1:
                    row_str += "█ "
                else:
                    row_str += "  "
            print(row_str + "|")
        print("=" * (self.width * 2 + 2))
